/*
 * This source file was generated by the Gradle 'init' task
 */
package practicefinal3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class PracticeTest3 {
    
    @Test
    void TestMaxDifference(){
        Practice practice = new Practice();
        int[] data = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        assertEquals(9, practice.max_difference(data));
    }

    @Test
    void TestMaxDifference1(){
        Practice practice = new Practice();
        int[] data = {-4, 17, 3, 6, 7, 90, -32};
        assertEquals(122, practice.max_difference(data));
    }

}
